// Cloudflare Pages middleware.
//
// Two jobs, both about answering machines without changing what a person sees:
//
//   1. Markdown for Agents. A request that asks for text/markdown (and does not
//      prefer HTML) gets the page's prebuilt Markdown, generated by build.mjs
//      from the same source as the HTML. Everything else is untouched HTML.
//   2. Short aliases: /ai/ serves the agent entry document, and /ai/index.ilang
//      is served as plain text rather than an unknown binary type.
//
// The negotiated answer is never stored by a shared cache (no-store plus
// Vary: Accept), so an HTML request can never be served a Markdown body or the
// other way round.

const PAGE_DATA = "/agent-data/pages.json";
let cache = { at: 0, pages: null };

async function pageIndex(env, request) {
  if (cache.pages && Date.now() - cache.at < 60_000) return cache.pages;
  const res = await env.ASSETS.fetch(new URL(PAGE_DATA, request.url));
  if (!res.ok) return null;
  const data = await res.json();
  const byPath = new Map();
  for (const page of data.pages) byPath.set(page.path, page);
  cache = { at: Date.now(), pages: byPath };
  return byPath;
}

// Minimal Accept parsing: returns the quality for a given media type.
function quality(accept, type) {
  let best = 0;
  for (const part of accept.split(",")) {
    const [range, ...params] = part.trim().split(";");
    const q = params
      .map((p) => p.trim())
      .filter((p) => p.startsWith("q="))
      .map((p) => Number.parseFloat(p.slice(2)))[0];
    const value = Number.isFinite(q) ? q : 1;
    const [t, s] = range.trim().toLowerCase().split("/");
    if (t === "*" && s === "*") best = Math.max(best, value);
    else if (t === type.split("/")[0] && (s === "*" || s === type.split("/")[1])) best = Math.max(best, value);
  }
  return best;
}

function wantsMarkdown(request) {
  const accept = request.headers.get("Accept") || "";
  if (!/text\/markdown/i.test(accept)) return false;
  const md = quality(accept, "text/markdown");
  const html = quality(accept, "text/html");
  return md > 0 && md >= html;
}

async function serveMarkdown(env, request, file, extra) {
  const res = await env.ASSETS.fetch(new URL(file, request.url));
  if (!res.ok) return null;
  const body = await res.text();
  return new Response(body, {
    status: 200,
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
      Vary: "Accept",
      "Cache-Control": "no-store",
      "x-markdown-tokens": String(Math.max(1, Math.round(body.length / 4))),
      ...extra,
    },
  });
}

export async function onRequest(context) {
  const { request, env, next } = context;
  const url = new URL(request.url);
  const path = url.pathname;

  if (request.method !== "GET" && request.method !== "HEAD") return next();

  if (path === "/ai/" || path === "/ai") {
    const res = await serveMarkdown(env, request, "/ai/index.md", { Vary: "Accept" });
    if (res) return res;
  }

  if (path === "/ai/index.ilang") {
    const res = await env.ASSETS.fetch(request);
    if (res.ok) {
      return new Response(await res.text(), {
        status: 200,
        headers: { "Content-Type": "text/plain; charset=utf-8", "Cache-Control": "public, max-age=300" },
      });
    }
  }

  if (!wantsMarkdown(request)) return next();

  const pages = await pageIndex(env, request);
  const page = pages?.get(path);
  if (page) {
    const res = await serveMarkdown(env, request, "/" + page.markdown_file, {});
    if (res) return res;
  }
  return next();
}
